services:
  app-log:
    build: .
    container_name: app-log
    ports:
      - "8080:8080"
    depends_on:
      - alloy
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    volumes:
      - ./infra/alloy/config.alloy:/etc/alloy/config.alloy
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    ports:
      - "12345:12345"
      - "3101:3100" # Expose Alloy's receiver port to host on 3101 just in case
    depends_on:
      - loki

  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    volumes:
      - ./infra/loki/local-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./infra/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    depends_on:
      - loki

  action-service:
    build: ./action-service
    container_name: action-service
    ports:
      - "5001:5000"
